version: '3'

services:
  api:
    image: habib926653/videoapidjango:latest
    ports:
      - "9200:80"
    environment:
      - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
      - AWS_STORAGE_BUCKET_NAME=YOUR_S3_BUCKET_NAME
      - AWS_S3_REGION_NAME=YOUR_BUCKET_REGION

  frontend:
    image: habib926653/api_frontend:latest
    ports:
      - "80:80"
